/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Dinonum.types";
import * as _1 from "./Dinonum.client";
import * as _2 from "./Dinonum.message-composer";
export namespace contracts {
  export const Dinonum = {
    ..._0,
    ..._1,
    ..._2
  };
}